language: python

python:
    - "2.6"
    - "2.7"

branches:
    only:
        - master
        - develop

install:
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse; fi"

script: make test
