language: python

python:
    - "2.7"

env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=cov

branches:
    only:
        - master
        - develop

before_install:
 - sudo add-apt-repository ppa:intact/python-gflags
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-gflags

install: pip install --quiet --use-mirrors tox

script: tox

after_script:
    - if [ $TOXENV == "cov" ]; then
        pip install --quiet --use-mirrors coveralls;
        coveralls;
      fi
